services:
  backend:
    build:
      dockerfile: Dockerfile
    volumes:
      - ./backend:/code/backend
      - ./tests:/code/tests
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/project_tracker
      MCP_SERVER_URL: http://mcp:4000/mcp
    container_name: project-tracker-backend-fastapi
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: project-tracker-db-1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: project_tracker
    ports:
      - "5432:5432"
